/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as PayRouteImport } from './routes/pay'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordsOrderIdRouteImport } from './routes/records.$orderId'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsOrderIdRoute = RecordsOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => RecordsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pay': typeof PayRoute
  '/records': typeof RecordsRouteWithChildren
  '/success': typeof SuccessRoute
  '/records/$orderId': typeof RecordsOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pay': typeof PayRoute
  '/records': typeof RecordsRouteWithChildren
  '/success': typeof SuccessRoute
  '/records/$orderId': typeof RecordsOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pay': typeof PayRoute
  '/records': typeof RecordsRouteWithChildren
  '/success': typeof SuccessRoute
  '/records/$orderId': typeof RecordsOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pay' | '/records' | '/success' | '/records/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pay' | '/records' | '/success' | '/records/$orderId'
  id: '__root__' | '/' | '/pay' | '/records' | '/success' | '/records/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PayRoute: typeof PayRoute
  RecordsRoute: typeof RecordsRouteWithChildren
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$orderId': {
      id: '/records/$orderId'
      path: '/$orderId'
      fullPath: '/records/$orderId'
      preLoaderRoute: typeof RecordsOrderIdRouteImport
      parentRoute: typeof RecordsRoute
    }
  }
}

interface RecordsRouteChildren {
  RecordsOrderIdRoute: typeof RecordsOrderIdRoute
}

const RecordsRouteChildren: RecordsRouteChildren = {
  RecordsOrderIdRoute: RecordsOrderIdRoute,
}

const RecordsRouteWithChildren =
  RecordsRoute._addFileChildren(RecordsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PayRoute: PayRoute,
  RecordsRoute: RecordsRouteWithChildren,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
